baseURL = "/"
languageCode = "en-us"
title = "Hugo Site"
theme = "hyde"

[params]
    description = "...solving error is the best solution as they say!!"
    copyright = "@j 2018. All Rights Reserved by J's."

[permalinks]
    post = "/:year/:month/:day/:slug/" 